### ISSUE TITLE
Change python to python3 in setup.py?

### ISSUE THREAD

**Issue by jelber2** [brendanofallon/jovian#41]
Should this read `python3` and not `python` ? Had to make a symbolic link in my container for Ubuntu 20.04 pointing from python3 to python.

https://github.com/brendanofallon/jovian/blob/dcbd3c5e133f59e3cefd9ea0212132109896bfea/setup.py#L28C1-L28C18

**Comment by brendanofallon** [comment]
Good point. On most modern linux systems `python` is an alias for python 3, but apparently not all.  Jenever (and the earlier version, Jovian) do require python >= 3.10, but there's not a good, explicit check for this anywhere, that would be a good thing to add to the setup.py somewhere. 
 Let me know how it goes with the long read data.  Jenever was trained exclusively on Illumina short reads from WGS samples, so not sure what the results will look like!

**Comment by jelber2** [comment]
Thanks. I will reply to the long read question in that Issue.
